default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  port: 5433
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USER_NAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

test:
  <<: *default
  database: kan_care_test

production:
  <<: *default
  database: kan_care_production
  username: kan_care
  password: <%= ENV['KAN_CARE_DATABASE_PASSWORD'] %>
